/*****************************************************************************
*
*  TITLE:       Copy File
*
*  DESCRIPTION: This program copies file(s) with many options.  Run the
*               program with "-?" to see the options.
*
*  *k "%n"
*  FILE NAME: ""
*
*  *k "%v"
*  VERSION:   ""
*
*****************************************************************************/

#include <ctype.h>
#include <dir.h>
#include <dos.h>
#include <stdarg.h>
#include <stdio.h>

