#ifndef __icitypes
#define __icitypes


typedef unsigned long int  UINT32;
typedef unsigned short int UINT16;
typedef unsigned char      UINT8;

typedef unsigned int       UINT;

typedef long int  INT32;
typedef short int INT16;
typedef char      INT8;

typedef int       INT;

typedef unsigned int BIT;       /* used for bitfields */

typedef enum
{
   false = 0,
   true = 1
} BOOLEAN;


#endif

