#ifndef __z8530
#define __z8530
/*****************************************************************************
*
*  TITLE:        Zilog 8530 class
*
*  DESCRIPTION:  The class "ZILOG_8530"
*                provides types, data and methods
*                for accessing a Zilog 8530 chip.
*
*  *k "%n"
*  FILE NAME:    ""
*
*  *k "%v"
*  VERSION:      ""
*
*  REFERENCE:    r
*
*****************************************************************************/

#ifndef __icitypes
#include "icitypes.h"
#endif

#ifndef __zchannel
#include "zchannel.hpp"

class ZILOG_8530
{

/*-------------------------------------------------------------------------
   Source: "Class_D1.c"
  -------------------------------------------------------------------------*/

protected:

   UINT16 io_base;


};   // class ZILOG_8530

#endif
