/*****************************************************************************
*
*  TITLE:        TIME_OF_DAY
*
*  DESCRIPTION:  The subprogram "TIME_OF_DAY"
*                of class TIME_OF_DAY
*                creates a time of day
*                and sets the time
*                to 00:00:00.000.
*
*  *k "%n"
*  FILE NAME:    ""
*
*  *k "%v"
*  VERSION:      ""
*
*  REFERENCE:    None.
*
*****************************************************************************/

#include "timeoday.h"


TIME_OF_DAY::TIME_OF_DAY()
{
   Set(0, 0, 0, 0);

}   // TIME_OF_DAY::TIME_OF_DAY

