/*****************************************************************************
*
*  TITLE:        Count
*
*  DESCRIPTION:  The class method "Count"
*                of class BIT_STREAM
*                returns the number of bits
*                currently in the bit stream.
*
*  *k "%n"
*  FILE NAME:    "COUNT1.CPP"
*
*  *k "%v"
*  VERSION:      "1"
*
*  REFERENCE:    None.
*
*****************************************************************************/

#include "bit_stre.h"


UINT BIT_STREAM :: Count()
{
   return count;

}   // BIT_STREAM :: Count

