@echo  off
cls
rowcol  0  0
echo  (00,00)
rowcol  1  1
echo  (01,01)
rowcol  2  2
echo  (02,02)
rowcol  3  3
echo  (03,03)
rowcol  4  4
echo  (04,04)
rowcol  5  5
echo  (05,05)
rowcol  6  6
echo  (06,06)
rowcol  7  7
echo  (07,07)
rowcol  8  8
echo  (08,08)
rowcol  9  9
echo  (09,09)
rowcol 10 10
echo  (10,10)
rowcol 11 11
echo  (11,11)
rowcol 12 12
echo  (12,12)
rowcol 13 13
echo  (13,13)
rowcol 14 14
echo  (14,14)
